version: '3'

services:
  frontend:
    container_name: bsce-exchange-wallet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    restart: always